#!/bin/python
import sys
import re
lines = sys.stdin.readlines()

services = ['httpd', 'xrootd', 'other']
messages = {}

for service in services:
    messages[service] =  {}

for line in lines:
    process = line.split()[4]
    level = line.split()[5]

    if '!!!' not in level:
        continue

    if 'httpd' in process:
        process = 'httpd'
    elif 'xrootd' in process:
        process = 'xrootd'
    else:
        process = 'other'

    data = ' '.join(line.split()[6:])


    data_filter = ''
    for word in data.split():
        if re.match('\'\/dpm\/.*\/home\/.*\'', word):
            word = 'DPM_LFN'  

        if re.match('\/dpm\/.*\/home\/.*', word):
            word = 'DPM_LFN'  

        if re.match('\'\/.*\/\d{4}-\d{2}-\d{2}\/.*\'', word):
            word = 'DPM_TURL'  

        if re.match('\/.*\/\d{4}-\d{2}-\d{2}\/.*', word):
            word = 'DPM_TURL'  

        if '[0x' in word:
            word = 'HEXNUMBNER'
   
        if re.match('\'..\'', word): 
            word = 'RAMDOM_DIR'

        if word.isdigit():
            word = 'NUMBER'

        if re.match('\(\d+\)', word): 
            word = '(NUMBER)'

        if re.match('\(\d+', word): 
            word = '(NUMBER'

        if re.match('\d+,', word): 
            word = 'NUMBER,'

        if re.match('id\:\d+', word): 
            word = 'id:NUMBER,'

        if re.match('\d+\)', word): 
            word = 'NUMBER)'

        if re.match('\'\d+\-..\'', word): 
            word = 'FILE_KEY'

        # ATLAS experiment
        if re.match('.*\.pool\.root.*', word): 
            word = 'FILE_POOL_ROOT'

        if re.match('.*\.job\.log\.tgz.*', word):
            word = 'FILE_LOG_TGZ'

        if re.match('.*\.pic\.gz.*', word):
            word = 'FILE_PIC_GZ'

        if re.match('\d+\:\'.*\'', word): 
            word = 'FILE_NAME'

        if re.match('(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test).*\)\.', word): 
            word = 'FILE_NAME'
   
        if re.match('\'(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test)\..*\'', word):
            word = 'FILE_NAME'

        if re.match('.*(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test)\..*\.root\..*', word):
            word = 'FILE_NAME'

        if re.match('.*testfile.*ATLAS.*', word):
            word = 'ATLAS_TEST_FILE'

        data_filter = data_filter + ' ' + word 


    if data_filter in messages[process].keys():
        messages[process][data_filter] += 1
    else:
        messages[process][data_filter] = 1


for service in services:
    messages_sorted = sorted(messages[service].items(), 
                             key=lambda x:-x[1])

    print ('Process %s:' % service)

    for data in messages_sorted:
        count = str(data[1]).rjust(8)
        message = data[0] 

        print ('%s time(s) : %s' % (count, message))

    print ('\n')
