#!/bin/python
import sys
import re
lines = sys.stdin.readlines()

messages = {}

for line in lines:
    process = line.split()[4]
    level = line.split()[5]

    if '!!!' not in level:
        continue

    if 'httpd' in process:
        process = 'httpd'
    elif 'xrootd' in process:
        process = 'xrootd'
    elif 'globus-gridftp-server' in process:
        process = 'globus-gridftp-server'
    else:
        process = 'other'

    data = ' '.join(line.split()[6:])


    data_filter = ''
    for word in data.split():
        if re.match('\'\/dpm\/.*\/home\/.*\'', word):
            word = 'DPM_LFN'  

        if re.match('\/dpm\/.*\/home\/.*', word):
            word = 'DPM_LFN'  

        if re.match('\'\/.*\/\d{4}-\d{2}-\d{2}\/.*\'', word):
            word = 'DPM_TURL'  

        if re.match('\/.*\/\d{4}-\d{2}-\d{2}\/.*', word):
            word = 'DPM_TURL'  

        if '[0x' in word:
            word = 'HEXNUMBNER'
   
        if re.match('\'..\'', word): 
            word = 'RAMDOM_DIR'

        if word.isdigit():
            word = 'NUMBER'

        if re.match('\(\d+\)', word): 
            word = '(NUMBER)'

        if re.match('\(\d+', word): 
            word = '(NUMBER'

        if re.match('\d+,', word): 
            word = 'NUMBER,'

        if re.match('id\:\d+', word): 
            word = 'id:NUMBER,'

        if re.match('\d+\)', word): 
            word = 'NUMBER)'

        if re.match('\'\d+\-..\'', word): 
            word = 'FILE_KEY'

        # ATLAS experiment
        if re.match('.*\.pool\.root.*', word): 
            word = 'FILE_POOL_ROOT'

        if re.match('.*\.job\.log\.tgz.*', word):
            word = 'FILE_LOG_TGZ'

        if re.match('.*\.pic\.gz.*', word):
            word = 'FILE_PIC_GZ'

        if re.match('\d+\:\'.*\'', word): 
            word = 'FILE_NAME'

        if re.match('(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test).*\)\.', word): 
            word = 'FILE_NAME'
   
        if re.match('\'(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test)\..*\'', word):
            word = 'FILE_NAME'

        if re.match('.*(data|user|group|panda|log|NTUP|AOD|DAOD|EVNT|ESD|DESD|HITS|RDO|output|test)\..*\.root\..*', word):
            word = 'FILE_NAME'

        if re.match('.*testfile.*ATLAS.*', word):
            word = 'ATLAS_TEST_FILE'

        # ICEPP
        word = re.sub(r'data\d\d', 'dataXX', word)
        word = re.sub(r'lcg\-fs\d\d\d', 'lcg-fsXXX', word)
        word = re.sub(r'20\d\d\-\d\d\-\d\d', '20XX-XX-XX', word)

        data_filter = data_filter + ' ' + word 


    data_filter = process + ' : ' + data_filter 

    if data_filter in messages.keys():
        messages[data_filter] += 1
    else:
        messages[data_filter] = 1


messages_sorted = sorted(messages.items(), 
                             key=lambda x:-x[1])
for data in messages_sorted:
    count = str(data[1]).rjust(8)
    message = data[0] 

    print ('%s time(s) : %s' % (count, message))

print ('\n')
